
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],v=$('#v'),bar=$('#bar'),resetTop=$('#resetTop');
const S={hist:[],elig:{},acute:[],strong:[],thirst:'',vr:'',vc:'',cr:'',cs:'',vf:[],persist:'',bg:[]};
const P={intro:0,elig:10,q1:20,q1a:25,q2:35,q3:50,q3a:55,q4:65,q4a:70,q5:80,q5a:86,q6:94,result:100};
const VL={'0-1':'0〜1回','2-4':'2〜4回','5-6':'5〜6回','7plus':'7回以上','unknown':'覚えていない'},CL={'very-pale':'ほぼ無色〜ごく薄い黄色','yellow':'薄い黄色〜黄色','dark':'濃い黄色〜琥珀色','atypical':'赤・茶など普段の黄色系とは違う色','confounded':'ビタミン剤などのあとで普段とは違う鮮やかな色'};
const VOID={LS:'VOID_LOW_STRONG',L:'VOID_LOW',N:'VOID_NOT_LOW',U:'VOID_UNKNOWN',I:'VOID_INVALID',S:'VOID_SPECIAL'},COLOR={L:'COLOR_LOW',N:'COLOR_NOT_LOW',U:'COLOR_UNKNOWN',C:'COLOR_CONFOUNDED',A:'COLOR_ATYPICAL'},RES={M:'RESULT_MULTIPLE',P:'RESULT_PARTIAL',N:'RESULT_NOT_PROMINENT',U:'RESULT_UNCLEAR',V:'RESULT_VOID_SPECIAL',A:'RESULT_COLOR_ATYPICAL'};
function voidState(){let x=S.vr==='0-1'?(S.vc==='yes'?VOID.S:VOID.U):S.vr==='2-4'?VOID.LS:S.vr==='5-6'?VOID.L:S.vr==='7plus'?VOID.N:VOID.U;return S.vf.some(x=>x!=='none')?VOID.I:x}
function colorState(){if(S.cr!=='yes')return COLOR.U;return ['very-pale','yellow'].includes(S.cs)?COLOR.N:S.cs==='dark'?COLOR.L:S.cs==='atypical'?COLOR.A:S.cs==='confounded'?COLOR.C:COLOR.U}
function classify(a,b){if(b===COLOR.A)return RES.A;if(a===VOID.S)return RES.V;let l=[VOID.LS,VOID.L].includes(a),n=a===VOID.N,cl=b===COLOR.L,cn=b===COLOR.N;return l&&cl?RES.M:(l&&cn||n&&cl)?RES.P:n&&cn?RES.N:RES.U}
function track(event,p={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...p});window.dispatchEvent(new CustomEvent('karadaMapAnalytics',{detail:{event,...p}}));console.info('[preview]',event,p)}
function esc(x=''){return String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function prog(k){bar.style.width=(P[k]||0)+'%'}
function act(label='次へ'){return `<div class="act"><button id="back" class="btn secondary">戻る</button><button id="next" class="btn primary">${label}</button></div><div id="err" class="err"></div>`}function nav(fn){$('#back').onclick=back;$('#next').onclick=fn}function fail(t){$('#err').textContent=t}
function radio(n,val,t){return `<label class="opt"><input type="radio" name="${n}" value="${val}">${t}</label>`}function cb(n,val,t){return `<label class="opt"><input type="checkbox" name="${n}" value="${val}">${t}</label>`}function vals(n){return $$(`input[name=${n}]:checked`).map(x=>x.value)}function restore(n,x){if(Array.isArray(x))x.forEach(z=>{let e=$(`input[name=${n}][value="${z}"]`);if(e)e.checked=true});else if(x){let e=$(`input[name=${n}][value="${x}"]`);if(e)e.checked=true}}
function exclusive(n,special=['none','unknown']){$$(`input[name=${n}]`).forEach(e=>e.onchange=()=>{if(!e.checked)return;if(special.includes(e.value))$$(`input[name=${n}]`).forEach(x=>{if(x!==e)x.checked=false});else $$(`input[name=${n}]`).forEach(x=>{if(special.includes(x.value))x.checked=false})})}
function render(k){S.hist.push(k);prog(k);resetTop.classList.toggle('hide',k==='intro');({intro,elig,q1,q1a,q2,q3,q3a,q4,q4a,q5,q5a,q6,result}[k])()}
function back(){S.hist.pop();let k=S.hist.pop()||'intro';render(k)}function reset(){Object.assign(S,{hist:[],elig:{},acute:[],strong:[],thirst:'',vr:'',vc:'',cr:'',cs:'',vf:[],persist:'',bg:[]});render('intro')}resetTop.onclick=reset;
function intro(){v.innerHTML=`<h1>私、水分足りてる？</h1><p class="lead">直近24時間を振り返って、<b>水分不足側でみられやすい自己観察サイン</b>が、今の回答でどのくらい重なっているかを整理します。</p><div class="note">脱水症や熱中症を診断するものではありません。体内水分量や「1日○mL飲むべき」といった必要量も計算しません。</div><button id="start" class="btn primary" style="width:100%">チェックを始める</button>`;$('#start').onclick=()=>{track('water_check_start');render('elig')}}
function elig(){let q=[['age','18〜64歳です'],['preg','現在、妊娠中・授乳中ではありません'],['doctor','医師から水分量や水分のとり方について個別の指示を受けていません']];v.innerHTML=`<div class="qt">まず、利用条件を確認します</div><p class="help">初版は、日常の自己観察として同じ条件で見やすい範囲に対象を絞っています。</p>${q.map(([n,t])=>`<div class="gate"><b>${t}</b><div class="yn"><label><input name=${n} type=radio value=yes>はい</label><label><input name=${n} type=radio value=no>いいえ</label></div></div>`).join('')}${act()}`;q.forEach(([n])=>restore(n,S.elig[n]));nav(()=>{let o={};for(let [n]of q){let e=$(`input[name=${n}]:checked`);if(!e)return fail('3項目すべて選んでください。');o[n]=e.value}S.elig=o;Object.values(o).includes('no')?scope():render('q1')})}
function scope(){prog('result');let a=[];if(S.elig.age==='no')a.push('初版は18〜64歳を対象にした基準のため、同じ見方をそのまま当てはめません。');if(S.elig.preg==='no')a.push('妊娠中・授乳中は通常時と同じ条件で扱わないため、通常結果を出しません。');if(S.elig.doctor==='no')a.push('個別の水分指示がある場合は、その指示を優先します。');stop('今回は通常のチェック対象外です',a.join('<br><br>'),'このツールの結果を無理に当てはめず、今の条件に合う個別の案内や医療者の指示を優先してください。','SCOPE_STOP')}
function q1(){v.innerHTML=`<div class="qt">今、次のような普段とは違う体調不良がありますか？</div><p class="help">当てはまるものをすべて選んでください。</p><div class="opts">${cb('acute','vomit','嘔吐や下痢が繰り返している')}${cb('acute','fever','発熱などで、明らかに普段と違う体調不良がある')}${cb('acute','heat','暑い場所にいたあと、めまい・頭痛・吐き気・強いだるさなどがある')}${cb('acute','none','どれもない')}</div>${act()}`;restore('acute',S.acute);exclusive('acute',['none']);nav(()=>{let x=vals('acute');if(!x.length)return fail('いずれかを選んでください。');S.acute=x;x.includes('none')?render('q2'):render('q1a')})}
function q1a(){v.innerHTML=`<div class="qt">次のような状態もありますか？</div><div class="opts">${cb('strong','drink','自力で水分をとるのが難しい')}${cb('strong','conf','意識がぼんやりする、反応がおかしい')}${cb('strong','faint','失神・けいれんなどがある')}${cb('strong','none','どれもない')}</div>${act()}`;restore('strong',S.strong);exclusive('strong',['none']);nav(()=>{let x=vals('strong');if(!x.length)return fail('いずれかを選んでください。');S.strong=x;x.includes('none')?acuteStop():urgent()})}
function acuteStop(){let heat=S.acute.includes('heat'),next=heat?'暑い環境のあとに症状が出ている場合は、涼しい場所へ移り、衣服をゆるめて体を冷やしてください。意識がはっきりして自力で飲める場合は水分・塩分を補い、改善しない・悪化する場合は医療機関への相談を優先してください。':'今は日常のセルフチェックより、普段と違う体調への対応を優先してください。症状が続く、強くなる、心配がある場合は医療機関へ相談してください。';stop('今日は日常のQuick Checkをここで終了します','普段とは違う急な体調不良があるため、このツールでは水分不足側かどうかを整理しません。今回の症状を「水分不足の証拠」として扱うこともしません。',next,'SAFETY_STOP')}
function urgent(){stop('このチェックより、今の体調への対応を優先してください','自力で水分をとれない、意識や反応がおかしい、失神・けいれんなどがある場合は、通常のセルフチェックを続けません。','<div class="alert urgent"><b>救急車を呼ぶなど、緊急の対応を優先してください。</b><br>意識や反応がおかしい人に、無理に飲み物を飲ませないでください。</div>','URGENT_STOP')}
function q2(){single('直近24時間、起きている時間に「飲み物がほしい」と感じる、のどの渇きはどのくらいありましたか？','ここは補助情報で、単独では結果を変えません。','thirst',[['none','ほとんどなかった'],['sometimes','ときどきあった'],['often','何度も、はっきり感じた'],['constant','ずっと強く感じた'],['unknown','よくわからない']],S.thirst,x=>{S.thirst=x;render('q3')})}
function q3(){single('昨日の今ごろから今日の今ごろまで、トイレでおしっこをした回数は何回くらいでしたか？','夜中に起きて行った分も含めます。','vr',[['0-1','0〜1回'],['2-4','2〜4回'],['5-6','5〜6回'],['7plus','7回以上'],['unknown','覚えていない']],S.vr,x=>{S.vr=x;x==='0-1'?render('q3a'):render('q4')})}
function q3a(){single('24時間全体で、本当に0〜1回くらいでしたか？','数え忘れがありそうなら、無理に確定しなくて大丈夫です。','vc',[['yes','はい、たぶん間違いない'],['forgot','数え忘れがありそう'],['unknown','よくわからない']],S.vc,x=>{S.vc=x;render('q4')})}
function q4(){single('直近24時間の尿の色を、だいたい思い出せますか？','見ていなかった・確認しにくかった場合は「わからない」が正規の回答です。','cr',[['yes','はい、だいたいわかる'],['not-seen','見ていなかった／覚えていない'],['hard','トイレのつくりや照明などで確認しにくかった'],['varied','色がかなりばらついていて決めにくい']],S.cr,x=>{S.cr=x;x==='yes'?render('q4a'):render('q5')})}
function q4a(){v.innerHTML=`<div class="qt">日中に見た尿は、全体としてどの色に近いことが多かったですか？</div><p class="help">色は参考です。照明・便器の水・画面表示で見え方が変わるため、厳密な色見本ではありません。</p><div class="sw"><div><b style="background:#fff9cf"></b>ごく薄い黄色</div><div><b style="background:#f7e36d"></b>黄色</div><div><b style="background:#c48a2b"></b>濃い黄色〜琥珀色</div></div><div class="opts">${[['very-pale','ほぼ無色〜ごく薄い黄色'],['yellow','薄い黄色〜黄色'],['dark','濃い黄色〜琥珀色'],['atypical','赤・茶など、普段の黄色系とは違う色'],['confounded','ビタミン剤などのあとで、普段とは違う鮮やかな色だった'],['unknown','やっぱり判断できない']].map(x=>radio('cs',...x)).join('')}</div>${act()}`;restore('cs',S.cs);nav(()=>{let e=$('input[name=cs]:checked');if(!e)return fail('いずれかを選んでください。');S.cs=e.value;render('q5')})}
function q5(){v.innerHTML=`<div class="qt">次のうち、当てはまることはありますか？</div><p class="help">トイレ回数を水分のサインとして読みやすい条件か確認します。薬名は答えなくて大丈夫です。</p><div class="opts">${cb('vf','frequent-small','普段から、少量ずつ何度もトイレに行くことが多い')}${cb('vf','urinary-symptoms','排尿時の痛み、強い尿意、残尿感などがある')}${cb('vf','med-change','最近、薬を始めたり変えたりしてから、回数が明らかに変わった')}${cb('vf','diuretic-info','医師や薬剤師から「尿が増えることがある薬」と説明されたことがある')}${cb('vf','none','特にない')}</div>${act()}`;restore('vf',S.vf);exclusive('vf',['none']);nav(()=>{let x=vals('vf');if(!x.length)return fail('いずれかを選んでください。');S.vf=x;S.thirst==='constant'&&(x.includes('frequent-small')||x.includes('urinary-symptoms'))?render('q5a'):render('q6')})}
function q5a(){single('この強いのどの渇きやトイレの多さは、ここ数日以上続いていますか？','結果ランクには加点せず、別の注意欄にだけ使います。','persist',[['yes','はい'],['no','いいえ'],['unknown','わからない']],S.persist,x=>{S.persist=x;render('q6')})}
function q6(){v.innerHTML=`<div class="qt">直近24時間に、当てはまるものはありましたか？</div><p class="help">生活背景として結果説明に使い、結果ランクは変えません。</p><div class="opts">${cb('bg','heat','暑い場所や高温多湿の環境に長くいた')}${cb('bg','sweat','いつもより汗をかいた')}${cb('bg','gap','数時間、ほとんど飲み物をとらない時間があった')}${cb('bg','less','普段より飲み物が少なかった')}${cb('bg','restrict','むくみやトイレ回数が気になり、意識して水分を控えた')}${cb('bg','none','特にない')}${cb('bg','unknown','よくわからない')}</div>${act('結果を見る')}`;restore('bg',S.bg);exclusive('bg');nav(()=>{let x=vals('bg');if(!x.length)return fail('いずれかを選んでください。');S.bg=x;render('result')})}
function single(title,help,n,opts,old,done){v.innerHTML=`<div class="qt">${title}</div><p class="help">${help}</p><div class="opts">${opts.map(x=>radio(n,...x)).join('')}</div>${act()}`;restore(n,old);nav(()=>{let e=$(`input[name=${n}]:checked`);if(!e)return fail('いずれかを選んでください。');done(e.value)})}
function reason(a,b){let x=[];if(a===VOID.LS)x.push('24時間の排尿回数が2〜4回でした。水分不足側でみられやすいサインのひとつとして扱います。');else if(a===VOID.L)x.push('24時間の排尿回数が5〜6回でした。水分不足側でみられやすいサインのひとつとして扱います。');else if(a===VOID.N)x.push('24時間の排尿回数は7回以上でした。今回は不足側サインとして扱いません。');else if(a===VOID.I)x.push('排尿回数は水分以外の影響を受けている可能性があるため、今回は主判定に使いません。');else if(a===VOID.U)x.push('24時間の排尿回数をはっきり思い出せなかったため、今回は主判定に使いません。');if(b===COLOR.L)x.push('尿色は「濃い黄色〜琥珀色」に近い回答でした。水分不足側でみられやすいサインとして扱います。');else if(b===COLOR.N)x.push('尿色は「ほぼ無色〜黄色」側でした。今回は不足側サインとして扱いません。');else if(b===COLOR.C)x.push('ビタミン剤などの影響で普段と違う色だったため、今回は尿色を主判定に使いません。');else if(b===COLOR.U)x.push('尿色を確認できなかった／決めにくかったため、今回は主判定に使いません。');return x}
function result(){let a=voidState(),b=colorState(),r=classify(a,b);if(r===RES.V)return voidSpecial();if(r===RES.A)return colorSpecial();let low=[VOID.LS,VOID.L].includes(a),title,why,next;if(r===RES.M){title='水分不足側のサインが複数みられました';why='24時間のトイレ回数と尿色の両方に、今回のチェックで水分不足側として扱うサインがみられました。';next='次の24時間でも、飲み方を少し意識した日に、尿色とトイレ回数がどう変わるかを見てみてください。固定の○mLではなく、変化を観察することが手がかりになります。'}else if(r===RES.P){title='水分不足側のサインが一部みられました';why=(low?'24時間のトイレ回数':'尿色')+'には不足側サインがみられましたが、2つの主なサインは同じ方向ではありません。ひとつだけで決めず「一部」と整理します。';next='別の日にも同じ傾向が続くか、次に気になった日に尿色と24時間の回数を並べて見てみてください。'}else if(r===RES.N){title='今の回答では、水分不足側のサインは目立ちませんでした';why='今回の24時間では、トイレ回数と尿色のどちらにも、このチェックで不足側として扱うサインは目立ちませんでした。';next='これは「水分が十分」と保証する結果ではありません。暑さ・発汗・体調が変わった日には、同じ2点を観察材料にしてください。'}else{title='今回の回答だけでは、はっきり判断しにくい結果でした';why='尿色またはトイレ回数を、水分のサインとして使いにくい回答条件がありました。<ul>'+reason(a,b).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';next='答えられなかったことは失敗ではありません。次に日中トイレへ行ったとき、一度だけ尿色を意識するなど、確認しやすいところからで十分です。'}showResult(title,why,next,r)}
function bg(){let m={heat:'暑い場所・高温多湿',sweat:'いつもより発汗が多かった',gap:'数時間ほとんど飲まない時間があった',less:'普段より飲み物が少なかった',restrict:'むくみやトイレ回数が気になり、水分を控えた'},x=S.bg.filter(z=>m[z]);return x.length?'<ul>'+x.map(z=>'<li>'+m[z]+'</li>').join('')+'</ul><p>背景として返しますが、結果ランクは変えていません。</p>':'<p>今回、追加する生活背景は特にありませんでした。「特にない」「よくわからない」でも判定の失敗ではありません。</p>'}
function caution(){let x=[];if(S.thirst==='constant')x.push('強いのどの渇きがありました。口渇は今回の結果ランクを変えていません。');if(S.persist==='yes')x.push('強いのどの渇きとトイレの多さが数日以上続いています。水分のとり方だけでは説明できないこともあるため、この結果とは別に医療機関へ相談する選択肢もあります。');return x.length?'<div class="alert">'+x.join('<br><br>')+'</div>':''}
function cta(r){let t='水分の見直し方をもう少し読む',u='https://note.com/karadamap/n/n40fe4b48c3f7',d='足のむくみと水分をどう分けて見るかを整理しています。',route='water-swelling';if(S.bg.includes('heat')||S.bg.includes('sweat')){t='夏の不調の見方を読む';u='https://note.com/karadamap/n/ndcedbf647930';d='暑さだけで決めつけず、夏に体調が崩れる背景を分けて見る記事です。';route='summer-condition'}if(S.bg.includes('restrict')){t='むくみで水分を控える前に読む';u='https://note.com/karadamap/n/n40fe4b48c3f7';d='「飲む／控える」を決める前に、分けて見たいことを整理しています。';route='water-swelling'}if(S.bg.includes('gap')&&!S.bg.some(x=>['heat','sweat','restrict'].includes(x))){t='水分補給をやめる前に、飲み方を見直す';u='https://note.com/karadamap/n/n63de9b7e113d';d='冷たさ・量・速さ・タイミングなど、飲み方を分けて見る記事です。';route='drinking-pattern'}return `<div class="cta"><p>${d}</p><a id="cta" data-route="${route}" href="${u}" target="_blank" rel="noopener">${t}</a></div>`}
function showResult(title,why,next,r){prog('result');v.innerHTML=`<div class="rt">${title}</div><div class="obs"><div><small>24時間のトイレ回数</small>${esc(VL[S.vr]||'確認できず')}</div><div><small>尿色</small>${esc(S.cr==='yes'?(CL[S.cs]||'確認できず'):'確認できず')}</div></div><div class="block"><h2>この結果になった理由</h2><p>${why}</p></div><div class="block"><h2>こんな背景もありました</h2>${bg()}</div><div class="block"><h2>次に見ること</h2><p>${next}</p></div>${caution()}${cta(r)}<div class="note">脱水症や熱中症を診断する結果ではありません。「水分が十分」と保証する結果でもありません。</div>${endButtons()}`;finish(r,false)}
function voidSpecial(){prog('result');v.innerHTML=`<div class="rt">通常の4結果には当てはめません</div><div class="block"><h2>なぜ？</h2><p>24時間の排尿回数が0〜1回で、再確認してもそのくらいだったためです。このチェックでは、これを「水分不足が強い」と自動判定しません。排尿回数だけから尿量や不足の程度は決められません。</p></div><div class="block"><h2>次に見ること</h2><p>普段より明らかに少ない状態が続く、体調の変化がある、心配がある場合は、セルフチェックだけで様子を決めず医療機関へ相談してください。</p></div>${endButtons()}`;finish(RES.V,true)}
function colorSpecial(){prog('result');v.innerHTML=`<div class="rt">尿色は、水分チェックとは別に扱います</div><div class="block"><h2>なぜ？</h2><p>赤・茶など普段の黄色系とは違う色は、水分不足側のサインとして判定しません。水分以外の理由で変わることもあります。</p></div><div class="block"><h2>次に見ること</h2><p>明らかに赤い尿やコーラ色に見える尿、普段と違う色が続く場合は、水分量だけの問題と決めず、早めに医療機関で確認してください。</p></div>${endButtons()}`;finish(RES.A,true)}
function stop(title,why,next,code){prog('result');v.innerHTML=`<div class="rt">${title}</div><div class="block"><h2>通常結果を出さない理由</h2><p>${why}</p></div><div class="block"><h2>今はここを優先</h2><p>${next}</p></div>${endButtons()}`;finish(code,true)}
function endButtons(){return `<div class="act"><button id="reset" class="btn secondary">最初からやり直す</button></div><details><summary>安全案内の参考</summary><ul><li><a target="_blank" href="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000212502.html">厚生労働省｜熱中症予防のために</a></li><li><a target="_blank" href="https://www.wbgt.env.go.jp/sp/heatillness_three_points.php">環境省｜熱中症予防情報サイト</a></li><li><a target="_blank" href="https://www.urol.or.jp/public/symptom/01.html">日本泌尿器科学会｜血尿</a></li></ul></details>`}
function finish(code,special){track('water_check_complete',{result_code:code,special_route:special});setTimeout(()=>{$('#reset').onclick=reset;let a=$('#cta');if(a)a.onclick=()=>track('water_check_result_cta_click',{result_code:code,route:a.dataset.route})})}
render('intro');
